[theme]
primaryColor = "#38EF7D"               # A modern, bright green for key elements
backgroundColor = "#121212"            # Deep dark gray for main background (better than pure black)
secondaryBackgroundColor = "#1E1E1E"   # Slightly lighter dark for containers
textColor = "#E0E0E0"                  # Soft white for readability
font = "sans serif"

[browser]
gatherUsageStats = false